; =======================================================================================================
;                                MF ADMIN TAGS ULTRA YAPILANDIRMASI
; =======================================================================================================
; Format:
; "SteamID/ValveID/Nick/@Yetki" "Tag Metni" "Tag Rengi" "Yazi Rengi" "Isim Rengi" "Bas Susleme" "Bas Renk" "Son Susleme" "Son Renk"
;
; Renkler:
; 1 = Yesil
; 2 = Kirmizi
; 3 = Mavi
; 4 = Sari / Normal (Varsayilan)
; 5 = Gri
; 6 = Takim Rengi
;
; "Kimlik/Nick/@Yetki" "Tag"     "TagRengi" "YaziRengi" "IsimRengi" "BasSusleme" "BasRenk" "SonSusleme" "SonRenk"
"STEAM_0:0:123456"     "KURUCU"   "2"        "1"         "2"         "{"          "4"       "}"          "4"
"VALVE_0:4:987654"     "ADMIN"    "1"        "4"         "3"         "["          "1"       "]"          "1"
"MochiFoxy"            "YONETICI" "2"        "4"         "1"         "["          "2"       "]"          "2"
"Queen"                "Mochi"    "2"        "1"         "4"         ""           "0"       " <3"        "1"
"@d"                   "VIP"      "5"        "1"         "4"         "{"          "5"       "}"          "5"
"@c"                   "KOMUTAN"  "1"        "1"         "4"         ""           "0"       ""           "0"
